controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


# user: 
#     path: 'api/v1/user'
#     controller: App\Controller\UserController:indexAction
#     methods: ['GET']

# user_create: 
#     path: 'api/v1/user'
#     controller: App\Controller\UserController:createAction
#     methods: ['POST']